import { Container, Typography } from "@mui/material";
import DDAppBar from "./DDAppBar";
import './App.css';


export default function Blog(){
    return(
        <>
            <DDAppBar props={{bgColor: '#425F57'}} />
            <Container>
                <Typography component='h4' variant='h5' paragraph
                   sx={{
                    fontFamily: 'Josefin Sans'
                }}>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ut condimentum nibh, non imperdiet lacus. Donec sagittis efficitur velit eget auctor. Nulla efficitur erat posuere consequat pharetra. Nunc id consequat velit. Quisque ultricies, mi quis vestibulum tempor, urna ante tempor ipsum, eu dictum leo leo vel tellus. Donec id nulla quis magna pharetra tempor at at urna. Pellentesque aliquet bibendum semper. Etiam sed euismod urna.
                    Proin sed laoreet mauris. Nulla accumsan justo vel leo venenatis, ac volutpat massa fermentum. Fusce a congue eros. Sed volutpat tempor elit, vel gravida velit tempus non. Vestibulum egestas at justo non lobortis. Donec placerat nisi erat, aliquam consequat tortor molestie eget. Sed varius, enim ac feugiat efficitur, magna orci tristique velit, et maximus quam purus et enim. Donec auctor orci quis fringilla pellentesque. Morbi elementum orci a feugiat lacinia. Quisque imperdiet egestas porttitor.
                    Mauris consequat metus quis lacinia efficitur. Donec at metus nulla. Morbi ac libero a nulla mollis consequat. Vivamus lectus massa, fringilla sit amet suscipit sit amet, gravida vitae nisi. In lacinia, orci a dictum finibus, enim dolor efficitur lectus, et elementum sapien felis sed orci. Suspendisse tincidunt feugiat nibh, vitae cursus eros eleifend vitae. Nulla sit amet velit hendrerit, viverra orci a, condimentum dui. Fusce ut ex ut nibh congue faucibus quis non sem. Sed semper mollis sem eu hendrerit. Pellentesque pretium tempor quam quis semper. Nullam vehicula feugiat posuere. Morbi eu sapien sit amet arcu consectetur tristique sed id sapien. Cras luctus molestie est, in vehicula dolor aliquet at.
                    Praesent iaculis molestie accumsan. Pellentesque ultrices mauris semper, euismod libero non, euismod massa. Suspendisse aliquet rutrum mauris ac ultricies. Proin auctor, felis in finibus sodales, dolor felis porta urna, ac interdum dui justo vel risus. Duis dignissim sem et risus ornare, vitae rhoncus ex dictum. Nam sagittis urna magna, a ultrices arcu malesuada sit amet. Duis et ultrices dui. Vivamus a ultrices erat. Nunc vehicula placerat faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce tempus tincidunt odio, sed lacinia mauris cursus fermentum.
                    In mollis dolor ante, facilisis viverra turpis lacinia rhoncus. Morbi sem nunc, lacinia vitae eros quis, gravida mollis urna. Sed ornare sapien dolor, vitae dictum sapien bibendum a. Aenean at ultricies metus. Etiam varius odio id arcu aliquam lobortis. Quisque molestie scelerisque auctor. Nulla eu rhoncus sem. Nunc congue efficitur arcu, nec sollicitudin mi tristique rutrum. Morbi dolor ligula, suscipit eu arcu suscipit, finibus vehicula ligula. Sed egestas erat id elit pharetra, molestie placerat ligula imperdiet. Quisque dapibus tortor vel felis tempor congue. Donec aliquet aliquam erat in eleifend.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ut condimentum nibh, non imperdiet lacus. Donec sagittis efficitur velit eget auctor. Nulla efficitur erat posuere consequat pharetra. Nunc id consequat velit. Quisque ultricies, mi quis vestibulum tempor, urna ante tempor ipsum, eu dictum leo leo vel tellus. Donec id nulla quis magna pharetra tempor at at urna. Pellentesque aliquet bibendum semper. Etiam sed euismod urna.
                    Proin sed laoreet mauris. Nulla accumsan justo vel leo venenatis, ac volutpat massa fermentum. Fusce a congue eros. Sed volutpat tempor elit, vel gravida velit tempus non. Vestibulum egestas at justo non lobortis. Donec placerat nisi erat, aliquam consequat tortor molestie eget. Sed varius, enim ac feugiat efficitur, magna orci tristique velit, et maximus quam purus et enim. Donec auctor orci quis fringilla pellentesque. Morbi elementum orci a feugiat lacinia. Quisque imperdiet egestas porttitor.
                    Mauris consequat metus quis lacinia efficitur. Donec at metus nulla. Morbi ac libero a nulla mollis consequat. Vivamus lectus massa, fringilla sit amet suscipit sit amet, gravida vitae nisi. In lacinia, orci a dictum finibus, enim dolor efficitur lectus, et elementum sapien felis sed orci. Suspendisse tincidunt feugiat nibh, vitae cursus eros eleifend vitae. Nulla sit amet velit hendrerit, viverra orci a, condimentum dui. Fusce ut ex ut nibh congue faucibus quis non sem. Sed semper mollis sem eu hendrerit. Pellentesque pretium tempor quam quis semper. Nullam vehicula feugiat posuere. Morbi eu sapien sit amet arcu consectetur tristique sed id sapien. Cras luctus molestie est, in vehicula dolor aliquet at.
                    Praesent iaculis molestie accumsan. Pellentesque ultrices mauris semper, euismod libero non, euismod massa. Suspendisse aliquet rutrum mauris ac ultricies. Proin auctor, felis in finibus sodales, dolor felis porta urna, ac interdum dui justo vel risus. Duis dignissim sem et risus ornare, vitae rhoncus ex dictum. Nam sagittis urna magna, a ultrices arcu malesuada sit amet. Duis et ultrices dui. Vivamus a ultrices erat. Nunc vehicula placerat faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce tempus tincidunt odio, sed lacinia mauris cursus fermentum.
                    In mollis dolor ante, facilisis viverra turpis lacinia rhoncus. Morbi sem nunc, lacinia vitae eros quis, gravida mollis urna. Sed ornare sapien dolor, vitae dictum sapien bibendum a. Aenean at ultricies metus. Etiam varius odio id arcu aliquam lobortis. Quisque molestie scelerisque auctor. Nulla eu rhoncus sem. Nunc congue efficitur arcu, nec sollicitudin mi tristique rutrum. Morbi dolor ligula, suscipit eu arcu suscipit, finibus vehicula ligula. Sed egestas erat id elit pharetra, molestie placerat ligula imperdiet. Quisque dapibus tortor vel felis tempor congue. Donec aliquet aliquam erat in eleifend.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ut condimentum nibh, non imperdiet lacus. Donec sagittis efficitur velit eget auctor. Nulla efficitur erat posuere consequat pharetra. Nunc id consequat velit. Quisque ultricies, mi quis vestibulum tempor, urna ante tempor ipsum, eu dictum leo leo vel tellus. Donec id nulla quis magna pharetra tempor at at urna. Pellentesque aliquet bibendum semper. Etiam sed euismod urna.
                    Proin sed laoreet mauris. Nulla accumsan justo vel leo venenatis, ac volutpat massa fermentum. Fusce a congue eros. Sed volutpat tempor elit, vel gravida velit tempus non. Vestibulum egestas at justo non lobortis. Donec placerat nisi erat, aliquam consequat tortor molestie eget. Sed varius, enim ac feugiat efficitur, magna orci tristique velit, et maximus quam purus et enim. Donec auctor orci quis fringilla pellentesque. Morbi elementum orci a feugiat lacinia. Quisque imperdiet egestas porttitor.
                    Mauris consequat metus quis lacinia efficitur. Donec at metus nulla. Morbi ac libero a nulla mollis consequat. Vivamus lectus massa, fringilla sit amet suscipit sit amet, gravida vitae nisi. In lacinia, orci a dictum finibus, enim dolor efficitur lectus, et elementum sapien felis sed orci. Suspendisse tincidunt feugiat nibh, vitae cursus eros eleifend vitae. Nulla sit amet velit hendrerit, viverra orci a, condimentum dui. Fusce ut ex ut nibh congue faucibus quis non sem. Sed semper mollis sem eu hendrerit. Pellentesque pretium tempor quam quis semper. Nullam vehicula feugiat posuere. Morbi eu sapien sit amet arcu consectetur tristique sed id sapien. Cras luctus molestie est, in vehicula dolor aliquet at.
                    Praesent iaculis molestie accumsan. Pellentesque ultrices mauris semper, euismod libero non, euismod massa. Suspendisse aliquet rutrum mauris ac ultricies. Proin auctor, felis in finibus sodales, dolor felis porta urna, ac interdum dui justo vel risus. Duis dignissim sem et risus ornare, vitae rhoncus ex dictum. Nam sagittis urna magna, a ultrices arcu malesuada sit amet. Duis et ultrices dui. Vivamus a ultrices erat. Nunc vehicula placerat faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce tempus tincidunt odio, sed lacinia mauris cursus fermentum.
                    In mollis dolor ante, facilisis viverra turpis lacinia rhoncus. Morbi sem nunc, lacinia vitae eros quis, gravida mollis urna. Sed ornare sapien dolor, vitae dictum sapien bibendum a. Aenean at ultricies metus. Etiam varius odio id arcu aliquam lobortis. Quisque molestie scelerisque auctor. Nulla eu rhoncus sem. Nunc congue efficitur arcu, nec sollicitudin mi tristique rutrum. Morbi dolor ligula, suscipit eu arcu suscipit, finibus vehicula ligula. Sed egestas erat id elit pharetra, molestie placerat ligula imperdiet. Quisque dapibus tortor vel felis tempor congue. Donec aliquet aliquam erat in eleifend.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ut condimentum nibh, non imperdiet lacus. Donec sagittis efficitur velit eget auctor. Nulla efficitur erat posuere consequat pharetra. Nunc id consequat velit. Quisque ultricies, mi quis vestibulum tempor, urna ante tempor ipsum, eu dictum leo leo vel tellus. Donec id nulla quis magna pharetra tempor at at urna. Pellentesque aliquet bibendum semper. Etiam sed euismod urna.
                    Proin sed laoreet mauris. Nulla accumsan justo vel leo venenatis, ac volutpat massa fermentum. Fusce a congue eros. Sed volutpat tempor elit, vel gravida velit tempus non. Vestibulum egestas at justo non lobortis. Donec placerat nisi erat, aliquam consequat tortor molestie eget. Sed varius, enim ac feugiat efficitur, magna orci tristique velit, et maximus quam purus et enim. Donec auctor orci quis fringilla pellentesque. Morbi elementum orci a feugiat lacinia. Quisque imperdiet egestas porttitor.
                    Mauris consequat metus quis lacinia efficitur. Donec at metus nulla. Morbi ac libero a nulla mollis consequat. Vivamus lectus massa, fringilla sit amet suscipit sit amet, gravida vitae nisi. In lacinia, orci a dictum finibus, enim dolor efficitur lectus, et elementum sapien felis sed orci. Suspendisse tincidunt feugiat nibh, vitae cursus eros eleifend vitae. Nulla sit amet velit hendrerit, viverra orci a, condimentum dui. Fusce ut ex ut nibh congue faucibus quis non sem. Sed semper mollis sem eu hendrerit. Pellentesque pretium tempor quam quis semper. Nullam vehicula feugiat posuere. Morbi eu sapien sit amet arcu consectetur tristique sed id sapien. Cras luctus molestie est, in vehicula dolor aliquet at.
                    Praesent iaculis molestie accumsan. Pellentesque ultrices mauris semper, euismod libero non, euismod massa. Suspendisse aliquet rutrum mauris ac ultricies. Proin auctor, felis in finibus sodales, dolor felis porta urna, ac interdum dui justo vel risus. Duis dignissim sem et risus ornare, vitae rhoncus ex dictum. Nam sagittis urna magna, a ultrices arcu malesuada sit amet. Duis et ultrices dui. Vivamus a ultrices erat. Nunc vehicula placerat faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce tempus tincidunt odio, sed lacinia mauris cursus fermentum.
                    In mollis dolor ante, facilisis viverra turpis lacinia rhoncus. Morbi sem nunc, lacinia vitae eros quis, gravida mollis urna. Sed ornare sapien dolor, vitae dictum sapien bibendum a. Aenean at ultricies metus. Etiam varius odio id arcu aliquam lobortis. Quisque molestie scelerisque auctor. Nulla eu rhoncus sem. Nunc congue efficitur arcu, nec sollicitudin mi tristique rutrum. Morbi dolor ligula, suscipit eu arcu suscipit, finibus vehicula ligula. Sed egestas erat id elit pharetra, molestie placerat ligula imperdiet. Quisque dapibus tortor vel felis tempor congue. Donec aliquet aliquam erat in eleifend.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ut condimentum nibh, non imperdiet lacus. Donec sagittis efficitur velit eget auctor. Nulla efficitur erat posuere consequat pharetra. Nunc id consequat velit. Quisque ultricies, mi quis vestibulum tempor, urna ante tempor ipsum, eu dictum leo leo vel tellus. Donec id nulla quis magna pharetra tempor at at urna. Pellentesque aliquet bibendum semper. Etiam sed euismod urna.
                    Proin sed laoreet mauris. Nulla accumsan justo vel leo venenatis, ac volutpat massa fermentum. Fusce a congue eros. Sed volutpat tempor elit, vel gravida velit tempus non. Vestibulum egestas at justo non lobortis. Donec placerat nisi erat, aliquam consequat tortor molestie eget. Sed varius, enim ac feugiat efficitur, magna orci tristique velit, et maximus quam purus et enim. Donec auctor orci quis fringilla pellentesque. Morbi elementum orci a feugiat lacinia. Quisque imperdiet egestas porttitor.
                    Mauris consequat metus quis lacinia efficitur. Donec at metus nulla. Morbi ac libero a nulla mollis consequat. Vivamus lectus massa, fringilla sit amet suscipit sit amet, gravida vitae nisi. In lacinia, orci a dictum finibus, enim dolor efficitur lectus, et elementum sapien felis sed orci. Suspendisse tincidunt feugiat nibh, vitae cursus eros eleifend vitae. Nulla sit amet velit hendrerit, viverra orci a, condimentum dui. Fusce ut ex ut nibh congue faucibus quis non sem. Sed semper mollis sem eu hendrerit. Pellentesque pretium tempor quam quis semper. Nullam vehicula feugiat posuere. Morbi eu sapien sit amet arcu consectetur tristique sed id sapien. Cras luctus molestie est, in vehicula dolor aliquet at.
                    Praesent iaculis molestie accumsan. Pellentesque ultrices mauris semper, euismod libero non, euismod massa. Suspendisse aliquet rutrum mauris ac ultricies. Proin auctor, felis in finibus sodales, dolor felis porta urna, ac interdum dui justo vel risus. Duis dignissim sem et risus ornare, vitae rhoncus ex dictum. Nam sagittis urna magna, a ultrices arcu malesuada sit amet. Duis et ultrices dui. Vivamus a ultrices erat. Nunc vehicula placerat faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce tempus tincidunt odio, sed lacinia mauris cursus fermentum.
                    In mollis dolor ante, facilisis viverra turpis lacinia rhoncus. Morbi sem nunc, lacinia vitae eros quis, gravida mollis urna. Sed ornare sapien dolor, vitae dictum sapien bibendum a. Aenean at ultricies metus. Etiam varius odio id arcu aliquam lobortis. Quisque molestie scelerisque auctor. Nulla eu rhoncus sem. Nunc congue efficitur arcu, nec sollicitudin mi tristique rutrum. Morbi dolor ligula, suscipit eu arcu suscipit, finibus vehicula ligula. Sed egestas erat id elit pharetra, molestie placerat ligula imperdiet. Quisque dapibus tortor vel felis tempor congue. Donec aliquet aliquam erat in eleifend.
                </Typography>
            </Container>
        </>
    );
}