const recipes = [
  // Vegan 
  [
    "Vegan Lentil Curry",
    "Chickpea Tikka Masala",
    "Vegan Lasagna",
    "Quinoa Salad with Roasted Vegetables",
    "Mushroom and Spinach Vegan Quesadillas",
    "Sweet Potato and Black Bean Tacos",
    "Vegan Shepherd's Pie",
    "Zucchini Noodles with Creamy Avocado Sauce",
    "Cauliflower Buffalo Wings",
    "Vegan Chocolate Chip Cookies",
    "Coconut Curry Lentil Soup",
    "Vegan Pad Thai",
    "Roasted Veggie Buddha Bowl",
    "Chickpea Salad Sandwich",
    "Vegan Stuffed Peppers",
    "Spaghetti Aglio e Olio",
    "Vegan Baked Ziti",
    "Black Bean and Corn Tacos",
    "Vegan Quinoa Chili",
    "Roasted Cauliflower Steaks",
    "Vegan Caesar Salad",
    "Butternut Squash Soup",
    "Mediterranean Quinoa Salad",
    "Vegan Banana Bread",
    "Vegan Mac and Cheese",
    "Chickpea Curry",
    "Vegan Sushi Rolls",
    "Vegan Mushroom Risotto",
    "Curried Lentil Soup",
    "Vegan Pesto Pasta",
    "Sweet Potato Black Bean Burgers",
    "Vegan Fajitas",
    "Vegan Apple Crisp",
    "Spinach and Mushroom Vegan Quiche",
    "Vegan French Toast",
    "Chickpea Coconut Curry",
    "Vegan BBQ Pulled Jackfruit Sandwiches",
    "Roasted Vegetable Quinoa Bowls",
    "Vegan Spinach Artichoke Dip",
    "Lentil Walnut Tacos",
    "Vegan Tofu Scramble",
    "Quinoa Stuffed Bell Peppers",
    "Vegan Chickpea Salad",
    "Mango Avocado Salsa",
    "Vegan Chocolate Mousse",
    "Ratatouille",
    "Vegan Blueberry Pancakes",
    "Vegan Corn Chowder",
    "Stuffed Acorn Squash",
    "Vegan Lemon Bars",
    "Chickpea Coconut Curry Stew",
    "Vegan Oatmeal Cookies",
    "Roasted Brussels Sprouts with Balsamic Glaze",
    "Vegan Tomato Soup",
    "Vegan Teriyaki Tofu Stir-Fry",
    "Mushroom Wellington",
    "Vegan Pumpkin Bread",
    "Vegan Buffalo Cauliflower Wings",
    "Quinoa Stuffed Mushrooms",
    "Vegan Carrot Cake",
    "Vegan Nachos",
    "Curried Cauliflower Soup",
    "Vegan Chocolate Avocado Pudding",
    "Zucchini Noodles with Tomato Sauce",
    "Vegan Sweet Potato Casserole",
    "Vegan Pecan Pie",
    "Vegan Lemon Poppy Seed Muffins",
    "Spicy Vegan Black Bean Burgers",
    "Vegan Coconut Curry Noodles",
    "Quinoa Stuffed Zucchini Boats",
    "Vegan Chocolate Brownies",
    "Vegan Spinach and Artichoke Pizza",
    "Roasted Chickpea Salad",
    "Vegan Almond Butter Cups",
    "Vegan BBQ Tofu Skewers",
    "Vegan Lentil Soup",
    "Vegan Caprese Salad",
    "Chickpea Curry Stuffed Sweet Potatoes",
    "Vegan Baked Falafel",
    "Vegan Chocolate Chip Banana Bread",
    "Vegan Pumpkin Soup",
    "Vegan Stuffed Mushrooms",
    "Tofu Veggie Stir-Fry",
    "Vegan Cranberry Orange Muffins",
    "Vegan Coconut Curry Lentils",
    "Mediterranean Couscous Salad",
    "Vegan Chocolate Peanut Butter Bars",
    "Vegan Breakfast Burrito",
    "Vegan Mushroom and Walnut Bolognese",
    "Cauliflower Curry",
    "Vegan Blueberry Smoothie",
    "Vegan Quinoa Stuffed Tomatoes",
    "Vegan Green Bean Casserole",
    "Vegan Sweet Potato Pie"
  ],
  // Gluten-free recipes
  [
    "Gluten-free Pasta Primavera",
    "Quinoa Stuffed Bell Peppers",
    "Gluten-free Banana Bread",
    "Spinach and Feta Stuffed Chicken Breast",
    "Quinoa Salad with Roasted Vegetables",
    "Grilled Lemon Herb Salmon",
    "Gluten-free Chocolate Chip Cookies",
    "Cauliflower Fried Rice",
    "Gluten-free Pizza",
    "Baked Lemon Herb Chicken Thighs",
    "Stuffed Zucchini Boats",
    "Gluten-free Blueberry Muffins",
    "Zucchini Noodles with Pesto",
    "Gluten-free Chicken Tenders",
    "Grilled Shrimp Skewers",
    "Gluten-free Chocolate Cake",
    "Quinoa and Black Bean Salad",
    "Gluten-free Lemon Bars",
    "Chicken and Vegetable Stir-Fry",
    "Gluten-free Peanut Butter Cookies",
    "Grilled Steak with Chimichurri Sauce",
    "Gluten-free Cauliflower Crust Pizza",
    "Caprese Stuffed Portobello Mushrooms",
    "Gluten-free Pumpkin Bread",
    "Baked Parmesan Crusted Chicken",
    "Gluten-free Brownies",
    "Lemon Garlic Roasted Vegetables",
    "Gluten-free Zucchini Bread",
    "Baked Salmon with Dill Sauce",
    "Gluten-free Quiche",
    "Cauliflower Pizza Bites",
    "Gluten-free Oatmeal Raisin Cookies",
    "Grilled Chicken with Mango Salsa",
    "Gluten-free Carrot Cake",
    "Shrimp Scampi with Zucchini Noodles",
    "Gluten-free Apple Crisp",
    "Greek Chicken Salad",
    "Gluten-free Chocolate Pudding",
    "Baked Teriyaki Salmon",
    "Gluten-free Quinoa Tabbouleh",
    "Roasted Asparagus with Lemon",
    "Gluten-free Raspberry Bars",
    "Garlic Herb Baked Cod",
    "Gluten-free Granola",
    "Stuffed Bell Peppers with Quinoa and Turkey",
    "Gluten-free Lemon Poppy Seed Muffins",
    "Greek Stuffed Chicken Breast",
    "Gluten-free Chocolate Chip Pancakes",
    "Baked Garlic Butter Shrimp",
    "Gluten-free Banana Pancakes",
    "Quinoa Stuffed Mushrooms",
    "Gluten-free Spinach and Feta Stuffed Chicken Breast",
    "Grilled Balsamic Chicken",
    "Gluten-free Apple Cinnamon Muffins",
    "Cauliflower Alfredo Sauce",
    "Gluten-free Chocolate Avocado Cookies",
    "Lemon Herb Grilled Chicken",
    "Gluten-free Quinoa Stuffed Peppers",
    "Roasted Brussels Sprouts with Balsamic Glaze",
    "Gluten-free Peanut Butter Energy Balls",
    "Baked Lemon Herb Salmon",
    "Gluten-free Mediterranean Pasta Salad",
    "Zucchini Noodles with Tomato Sauce",
    "Gluten-free Blueberry Pancakes",
    "Grilled Lemon Herb Chicken",
    "Gluten-free Cinnamon Rolls",
    "Baked Parmesan Crusted Salmon",
    "Gluten-free Cauliflower Rice Stir-Fry",
    "Caprese Stuffed Chicken Breast",
    "Gluten-free Oatmeal Chocolate Chip Cookies",
    "Lemon Garlic Shrimp",
    "Gluten-free Quinoa Salad",
    "Quinoa Stuffed Zucchini Boats",
    "Gluten-free Chocolate Coconut Bars",
    "Grilled Balsamic Shrimp Skewers",
    "Gluten-free Chicken Piccata",
    "Roasted Cauliflower Steaks",
    "Gluten-free Banana Oatmeal Cookies",
    "Greek Quinoa Salad",
    "Gluten-free Lemon Pound Cake",
    "Baked Garlic Butter Chicken Thighs",
    "Gluten-free Apple Pie",
    "Cauliflower Pizza Crust",
    "Gluten-free Chocolate Peanut Butter Cups",
    "Lemon Herb Baked Chicken",
    "Gluten-free Quinoa Breakfast Bowl",
    "Roasted Brussels Sprouts with Parmesan",
    "Gluten-free Raspberry Almond Thumbprint Cookies",
    "Grilled Lime Cilantro Chicken",
    "Gluten-free Caprese Pasta Salad",
    "Zucchini Noodles with Garlic Shrimp",
    "Gluten-free Blueberry Crisp",
    "Baked Parmesan Crusted Chicken Tenders",
    "Gluten-free Quinoa Stuffed Tomatoes",
    "Grilled Salmon with Lemon Dill Sauce",
    "Gluten-free Lemon Blueberry Muffins",
    "Cauliflower Fried Rice with Shrimp",
    "Gluten-free Banana Chocolate Chip Bread",
    "Greek Stuffed Zucchini",
    "Gluten-free Chocolate Hazelnut Cake",
    "Lemon Herb Grilled Salmon",
    "Gluten-free Quinoa Black Bean Burgers",
    "Roasted Asparagus with Parmesan",
    "Gluten-free Peanut Butter Banana Muffins",
    "Garlic Parmesan Baked Salmon",
    "Gluten-free Quinoa Pilaf",
    "Caprese Stuffed Portobello Mushrooms",
    "Gluten-free Raspberry Chocolate Chip Bars",
    "Baked Lemon Herb Chicken Drumsticks",
    "Gluten-free Mediterranean Quinoa Salad",
    "Zucchini Noodles with Pesto Chicken",
    "Gluten-free Apple Cinnamon Pancakes",
    "Grilled Balsamic Pork Chops",
    "Gluten-free Cinnamon Swirl Bread",
    "Baked Garlic Butter Shrimp Scampi",
    "Gluten-free Banana Walnut Bread",
    "Cauliflower Tacos with Lime Slaw",
    "Gluten-free Chocolate Chip Oatmeal Cookies",
    "Lemon Garlic Butter Baked Cod",
    "Gluten-free Quinoa Veggie Burgers",
    "Roasted Brussels Sprouts with Bacon",
    "Gluten-free Blueberry Lemon Bars",
    "Greek Lemon Herb Chicken Skewers",
    "Gluten-free Caprese Stuffed Chicken Breast",
    "Zucchini Noodles with Tomato Basil Chicken",
    "Gluten-free Peach Crisp",
    "Baked Parmesan Crusted Pork Chops",
    "Gluten-free Quinoa Stuffed Bell Peppers",
    "Grilled Lemon Garlic Shrimp",
    "Gluten-free Banana Chocolate Chip Muffins",
    "Cauliflower Rice Stir-Fry with Tofu",
    "Gluten-free Chocolate Coconut Truffles",
    "Lemon Herb Baked Cod Fish",
    "Gluten-free Quinoa Taco Salad",
    "Roasted Brussels Sprouts with Garlic",
    "Gluten-free Raspberry Thumbprint Cookies",
    "Baked Garlic Butter Pork Tenderloin",
    "Gluten-free Mediterranean Chickpea Salad",
    "Zucchini Noodles with Shrimp Scampi",
    "Gluten-free Blueberry Coffee Cake",
    "Grilled Balsamic Turkey Burgers",
    "Gluten-free Cinnamon Raisin Bagels",
    "Baked Lemon Herb Pork Chops",
    "Gluten-free Quinoa Fried Rice",
    "Cauliflower Buffalo Wings",
    "Gluten-free Banana Bread Pancakes",
    "Greek Stuffed Peppers",
    "Gluten-free Chocolate Hazelnut Truffles"
  ],
  // Desserts 
  [
    "Classic Chocolate Cake",
    "Homemade Apple Pie",
    "Strawberry Shortcake",
    "Blueberry Cheesecake",
    "Lemon Bars",
    "Chocolate Chip Cookies",
    "Raspberry Swirl Cheesecake",
    "Banana Bread",
    "Pumpkin Pie",
    "Vanilla Cupcakes",
    "Key Lime Pie",
    "Caramel Brownies",
    "Red Velvet Cake",
    "Oreo Truffles",
    "Chocolate Pudding",
    "Peanut Butter Cookies",
    "Cherry Crisp",
    "Coconut Macaroons",
    "Pecan Pie",
    "Carrot Cake",
    "Lemon Meringue Pie",
    "Fudgy Brownies",
    "S'mores Bars",
    "Chocolate Mousse",
    "Apple Crumble",
    "Vanilla Ice Cream",
    "Strawberry Shortcake Cupcakes",
    "Cheesecake Brownies",
    "Blueberry Cobbler",
    "Chocolate Eclairs",
    "Peanut Butter Pie",
    "Raspberry Chocolate Tart",
    "Sugar Cookies",
    "Mixed Berry Crisp",
    "Pumpkin Cheesecake",
    "Lemon Drizzle Cake",
    "Chocolate Chip Muffins",
    "Black Forest Cake",
    "Coconut Cream Pie",
    "Butter Pecan Ice Cream",
    "Banana Split",
    "Mint Chocolate Chip Cookies",
    "Strawberry Cheesecake Bars",
    "Apple Cinnamon Muffins",
    "Peach Cobbler",
    "Rice Pudding",
    "Chocolate Covered Strawberries",
    "Tiramisu",
    "Caramel Apple Crisp",
    "Vanilla Bean Panna Cotta",
    "Cherry Pie",
    "Chocolate Dipped Macaroons",
    "Pecan Sticky Buns",
    "Lemon Pound Cake",
    "Cannoli",
    "Peanut Butter Chocolate Chip Blondies",
    "Blueberry Pie",
    "Chocolate Souffle",
    "Raspberry Lemon Bars",
    "Snickerdoodle Cookies",
    "Mixed Berry Pie",
    "Pumpkin Roll",
    "Key Lime Bars",
    "Butterscotch Pudding",
    "Banana Nut Bread",
    "Mango Sorbet",
    "Strawberry Rhubarb Crisp",
    "Chocolate Fudge",
    "Apple Galette",
    "Vanilla Bean Ice Cream",
    "Lemon Blueberry Cupcakes",
    "Coconut Custard Pie",
    "Blackberry Cobbler",
    "Chocolate Peanut Butter Pie",
    "Raspberry White Chocolate Cheesecake",
    "Sugar Donuts",
    "Mixed Berry Tart",
    "Pumpkin Bread",
    "Lemon Curd",
    "Chocolate Chunk Cookies",
    "Blueberry Muffins",
    "Cherry Almond Cake",
    "Coconut Lime Bars",
    "Bananas Foster",
    "Mint Chocolate Chip Ice Cream",
    "Strawberry Shortcake Trifle",
    "Apple Crisp",
    "Vanilla Bean Cheesecake",
    "Lemon Poppy Seed Muffins",
    "Chocolate Banana Bread",
    "Pecan Pralines",
    "Salted Caramel Ice Cream",
    "Raspberry Almond Bars",
    "Snickerdoodle Blondies",
    "Mixed Berry Crumble Bars",
    "Pumpkin Donuts",
    "Key Lime Pie Bars",
    "Chocolate Lava Cake",
    "Berry Parfait",
    "Coconut Cream Cake",
    "Banana Cream Pie",
    "Mango Panna Cotta",
    "Strawberry Cheesecake Ice Cream",
    "Apple Cinnamon Pancakes",
    "Vanilla Bean Bundt Cake",
    "Lemon Raspberry Cupcakes",
    "Chocolate Pecan Pie",
    "Blueberry Crumb Bars",
    "Cherry Chocolate Chip Cookies",
    "Coconut Rice Pudding",
    "Banana Chocolate Chip Muffins",
    "Mint Chocolate Chip Cheesecake",
    "Strawberry Banana Smoothie Bowl",
    "Apple Cider Donuts",
    "Vanilla Bean Creme Brulee",
    "Lemon Bars with Shortbread Crust",
    "Chocolate Chip Cookie Dough Ice Cream",
    "Peanut Butter Cupcakes",
    "Mixed Berry Cobbler",
    "Pumpkin Spice Latte Cupcakes",
    "Key Lime Cheesecake Bars",
    "Chocolate Coconut Macaroons",
    "Raspberry Chocolate Chip Muffins",
    "Sugar Cookie Bars",
    "Blueberry Lemon Muffins",
    "Cherry Cheesecake",
    "Coconut Lime Cupcakes",
    "Banana Pudding",
    "Mango Pineapple Smoothie",
    "Strawberry Crumble",
    "Apple Streusel Coffee Cake",
    "Vanilla Bean Donuts",
    "Lemon Blueberry Bundt Cake",
    "Chocolate Covered Pretzels",
    "Peanut Butter Swirl Brownies",
    "Mixed Berry Clafoutis",
    "Pumpkin Spice Donuts",
    "Key Lime Coconut Bars",
    "Chocolate Raspberry Tart",
    "Banana Split Cupcakes",
    "Mint Chocolate Chip Milkshake",
    "Strawberry Rhubarb Pie",
    "Apple Cinnamon Donuts",
    "Vanilla Bean Pound Cake",
    "Lemon Raspberry Tart",
    "Chocolate Coconut Cupcakes",
    "Blueberry Cheesecake Bars",
    "Cherry Vanilla Ice Cream",
    "Coconut Lime Rice Pudding",
    "Banana Chocolate Chip Pancakes",
    "Mango Coconut Smoothie",
    "Strawberry Shortbread Bars",
    "Apple Crumble Pie",
    "Vanilla Bean Rice Pudding",
    "Lemon Blueberry Scones",
    "Chocolate Peanut Butter Fudge",
    "Peanut Butter Chocolate Chip Cookies",
    "Mixed Berry Galette",
    "Pumpkin Cheesecake Bars",
    "Key Lime Pie Milkshake",
    "Chocolate Covered Strawberries",
    "Raspberry White Chocolate Muffins",
    "Sugar Cookie Cups",
    "Blueberry Lemon Bars",
    "Cherry Almond Tart",
    "Coconut Lime Pound Cake",
    "Banana Oatmeal Cookies",
    "Mango Raspberry Smoothie",
    "Strawberry Cheesecake Pancakes",
    "Apple Cinnamon Bread",
    "Vanilla Bean Caramel Sauce",
    "Lemon Poppy Seed Pound Cake",
    "Chocolate Dipped Fruit",
    "Peanut Butter Cup Cheesecake",
    "Mixed Berry Smoothie",
    "Pumpkin Spice Pancakes",
    "Key Lime Pie Cupcakes",
    "Chocolate Chip Cookie Dough Bites",
    "Raspberry Almond Muffins",
    "Snickerdoodle Bars",
    "Blueberry Crumb Cake",
    "Cherry Chocolate Brownies",
    "Coconut Lime Cheesecake",
    "Banana Nut Muffins",
    "Mint Chocolate Chip Milkshake",
    "Strawberry Banana Popsicles",
    "Apple Fritters",
    "Vanilla Bean Biscotti",
    "Lemon Raspberry Pound Cake",
    "Chocolate Peanut Butter Bars",
    "Peanut Butter Chocolate Chip Muffins",
    "Mixed Berry Sorbet",
    "Pumpkin Spice Bread",
    "Key Lime Tart",
    "Chocolate Coconut Truffles",
    "Raspberry Chocolate Chip Cookies",
    "Sugar Cookie Truffles",
    "Blueberry Lemon Loaf",
    "Cherry Vanilla Cupcakes",
    "Coconut Lime Bars",
    "Banana Split Sundae",
    "Mint Chocolate Chip Cookies",
    "Strawberry Shortcake Ice Cream Bars",
    "Apple Cinnamon Crumb Bars",
    "Vanilla Bean Cheesecake Bars",
    "Lemon Blueberry Pancakes",
    "Chocolate Covered Almonds",
    "Peanut Butter Cup Pie",
    "Mixed Berry Smoothie Bowl",
    "Pumpkin Spice Cupcakes",
    "Key Lime Pie Truffles",
    "Chocolate Raspberry Cheesecake Bars",
    "Raspberry Almond Thumbprint Cookies",
    "Snickerdoodle Cheesecake",
    "Blueberry Coffee Cake",
    "Cherry Almond Clafoutis",
    "Coconut Lime Shortbread Cookies",
    "Banana Cream Trifle",
    "Mint Chocolate Chip Brownies",
    "Strawberry Banana Bread",
    "Apple Cinnamon Muffins",
    "Vanilla Bean Creme Brulee",
    "Lemon Raspberry Tartlets",
    "Chocolate Peanut Butter Ice Cream",
    "Peanut Butter Chocolate Chip Blondies",
    "Mixed Berry Tart",
    "Pumpkin Spice Donut Holes",
    "Key Lime Coconut Cupcakes",
    "Chocolate Raspberry Tartlets",
    "Raspberry Almond Bars",
    "Sugar Cookie Sandwiches",
    "Blueberry Lemon Pound Cake",
    "Cherry Cheesecake Bars",
    "Coconut Lime Panna Cotta",
    "Banana Chocolate Chip Bread",
    "Mint Chocolate Chip Cheesecake Bars",
    "Strawberry Shortcake Skewers",
    "Apple Crumb Muffins",
    "Vanilla Bean Yogurt Parfait",
    "Lemon Blueberry Bread",
    "Chocolate Covered Pretzel Rods",
    "Peanut Butter Cupcakes with Chocolate Ganache",
    "Mixed Berry Cobbler Bars",
    "Pumpkin Spice Latte Donuts",
    "Key Lime Pie Bars",
    "Chocolate Coconut Macaroon Tart",
    "Raspberry Chocolate Chip Cupcakes",
    "Snickerdoodle Cookie Bars",
    "Blueberry Crumble Bars",
    "Cherry Almond Cake",
    "Coconut Lime Cupcakes",
    "Banana Pudding Parfait",
    "Mint Chocolate Chip Ice Cream Sandwiches",
    "Strawberry Rhubarb Crisp Bars",
    "Apple Cinnamon Coffee Cake",
    "Vanilla Bean Donut Holes",
    "Lemon Blueberry Bundt Cake",
    "Chocolate Covered Marshmallows",
    "Peanut Butter Swirl Brownie Bars",
    "Mixed Berry Clafoutis",
    "Pumpkin Spice Donut Muffins",
    "Key Lime Coconut Bars",
    "Chocolate Raspberry Cheesecake Cups",
    "Raspberry Almond Muffins",
    "Sugar Cookie Bars with Cream Cheese Frosting",
    "Blueberry Lemon Muffins",
    "Cherry Cheesecake",
    "Coconut Lime Cupcakes",
    "Banana Pudding",
    "Mango Pineapple Smoothie",
    "Strawberry Crumble",
    "Apple Streusel Coffee Cake",
    "Vanilla Bean Donuts",
    "Lemon Blueberry Bundt Cake",
    "Chocolate Covered Pretzels",
    "Peanut Butter Swirl Brownies",
    "Mixed Berry Clafoutis",
    "Pumpkin Spice Donuts",
    "Key Lime Coconut Bars",
    "Chocolate Raspberry Tart",
    "Banana Split Cupcakes",
    "Mint Chocolate Chip Milkshake",
    "Strawberry Rhubarb Pie",
    "Apple Cinnamon Donuts",
    "Vanilla Bean Pound Cake",
    "Lemon Raspberry Tart",
    "Chocolate Coconut Cupcakes",
    "Blueberry Cheesecake Bars",
    "Cherry Vanilla Ice Cream",
    "Coconut Lime Rice Pudding",
    "Banana Chocolate Chip Pancakes",
    "Mango Coconut Smoothie",
    "Strawberry Shortbread Bars",
    "Apple Crumble Pie",
    "Vanilla Bean Rice Pudding",
    "Lemon Blueberry Scones",
    "Chocolate Peanut Butter Fudge",
    "Peanut Butter Chocolate Chip Cookies",
    "Mixed Berry Galette",
    "Pumpkin Cheesecake Bars",
    "Key Lime Pie Milkshake",
    "Chocolate Covered Strawberries",
    "Raspberry White Chocolate Muffins",
    "Sugar Cookie Cups",
    "Blueberry Lemon Bars",
    "Cherry Almond Tart",
    "Coconut Lime Pound Cake",
    "Banana Oatmeal Cookies",
    "Mango Raspberry Smoothie",
    "Strawberry Cheesecake Pancakes",
    "Apple Cinnamon Bread",
    "Vanilla Bean Caramel Sauce",
    "Lemon Poppy Seed Pound Cake",
    "Chocolate Dipped Fruit",
    "Peanut Butter Cup Cheesecake",
    "Mixed Berry Smoothie",
    "Pumpkin Spice Pancakes",
    "Key Lime Pie Cupcakes"
  ],
  // Keto
  [
    "Keto Cauliflower Fried Rice",
    "Keto Chocolate Fat Bombs",
    "Keto Avocado Egg Salad",
    "Keto Almond Flour Pancakes",
    "Keto Cheeseburger Casserole",
    "Keto Creamy Broccoli Soup",
    "Keto Coconut Flour Bread",
    "Keto Bacon-Wrapped Asparagus",
    "Keto Lemon Garlic Butter Salmon",
    "Keto Zucchini Noodles",
    "Keto Cheesy Cauliflower Rice",
    "Keto Peanut Butter Cookies",
    "Keto Chicken Alfredo",
    "Keto Avocado Shrimp Salad",
    "Keto Almond Flour Biscuits",
    "Keto Bacon-Wrapped Chicken Tenders",
    "Keto Cauliflower Mac and Cheese",
    "Keto Chocolate Mug Cake",
    "Keto Creamy Garlic Parmesan Chicken",
    "Keto Coconut Flour Pancakes",
    "Keto Cheesy Bacon Brussels Sprouts",
    "Keto Lemon Herb Chicken",
    "Keto Zucchini Fritters",
    "Keto Cheesy Broccoli Casserole",
    "Keto Peanut Butter Fat Bombs",
    "Keto Chicken Parmesan",
    "Keto Avocado Chicken Salad",
    "Keto Almond Flour Waffles",
    "Keto Bacon-Wrapped Shrimp",
    "Keto Cauliflower Pizza Crust",
    "Keto Chocolate Chia Pudding",
    "Keto Creamy Tuscan Garlic Chicken",
    "Keto Coconut Flour Tortillas",
    "Keto Cheesy Garlic Breadsticks",
    "Keto Lemon Bars",
    "Keto Zucchini Lasagna",
    "Keto Cheesy Cauliflower Breadsticks",
    "Keto Peanut Butter Chocolate Chip Cookies",
    "Keto Chicken Taco Casserole",
    "Keto Avocado Stuffed Burgers",
    "Keto Almond Flour Chocolate Chip Cookies",
    "Keto Bacon-Wrapped Jalapeno Poppers",
    "Keto Cauliflower Rice Stir-Fry",
    "Keto Chocolate Cheesecake Fat Bombs",
    "Keto Creamy Spinach Stuffed Chicken Breast",
    "Keto Coconut Flour Banana Bread",
    "Keto Cheesy Bacon Cauliflower Casserole",
    "Keto Lemon Pepper Chicken",
    "Keto Zucchini Bread",
    "Keto Cheesy Garlic Roasted Brussels Sprouts",
    "Keto Peanut Butter Cup Fat Bombs",
    "Keto Chicken Enchilada Casserole",
    "Keto Avocado Caprese Salad",
    "Keto Almond Flour Chocolate Cake",
    "Keto Bacon-Wrapped Meatloaf",
    "Keto Cauliflower Mash",
    "Keto Chocolate Peanut Butter Mug Cake",
    "Keto Creamy Garlic Parmesan Shrimp",
    "Keto Coconut Flour Brownies",
    "Keto Cheesy Bacon Spinach Dip",
    "Keto Lemon Garlic Butter Chicken Thighs",
    "Keto Zucchini Chips",
    "Keto Cheesy Cauliflower Tots",
    "Keto Peanut Butter Cheesecake",
    "Keto Chicken Bacon Ranch Casserole",
    "Keto Avocado Tuna Salad",
    "Keto Almond Flour Pizza Crust",
    "Keto Bacon-Wrapped Asparagus Bundles",
    "Keto Cauliflower Buffalo Wings",
    "Keto Chocolate Peanut Butter Fat Bombs",
    "Keto Creamy Sun-Dried Tomato Chicken",
    "Keto Coconut Flour Blueberry Muffins",
    "Keto Cheesy Bacon Ranch Cauliflower",
    "Keto Lemon Garlic Shrimp",
    "Keto Zucchini Fries",
    "Keto Cheesy Cauliflower Bites",
    "Keto Peanut Butter Chocolate Cheesecake",
    "Keto Chicken Cordon Bleu Casserole",
    "Keto Avocado Deviled Eggs",
    "Keto Almond Flour Banana Muffins",
    "Keto Bacon-Wrapped Brussels Sprouts",
    "Keto Cauliflower Gnocchi",
    "Keto Chocolate Peanut Butter Smoothie",
    "Keto Creamy Garlic Parmesan Zoodles",
    "Keto Coconut Flour Pancake Cereal",
    "Keto Cheesy Bacon Ranch Chicken",
    "Keto Lemon Garlic Butter Shrimp Skewers",
    "Keto Zucchini Pizza Bites",
    "Keto Cheesy Cauliflower Rice Casserole",
    "Keto Peanut Butter Chocolate Chip Fat Bombs",
    "Keto Chicken Stir-Fry",
    "Keto Avocado Lime Salmon",
    "Keto Almond Flour Blueberry Pancakes",
    "Keto Bacon-Wrapped Green Beans",
    "Keto Cauliflower Tater Tots",
    "Keto Chocolate Mousse",
    "Keto Creamy Pesto Chicken",
    "Keto Coconut Flour Pancake Tacos",
    "Keto Cheesy Bacon Ranch Zucchini Boats",
    "Keto Lemon Blueberry Muffins",
    "Keto Zucchini Noodle Alfredo",
    "Keto Cheesy Cauliflower Rice Skillet",
    "Keto Peanut Butter Chocolate Chip Cookies",
    "Keto Chicken and Broccoli Casserole",
    "Keto Avocado Shrimp Lettuce Wraps",
    "Keto Almond Flour Chocolate Chip Pancakes",
    "Keto Bacon-Wrapped Stuffed Mushrooms",
    "Keto Cauliflower Fried Chicken",
    "Keto Chocolate Peanut Butter Pie",
    "Keto Creamy Spinach and Mushroom Chicken",
    "Keto Coconut Flour Chocolate Donuts",
    "Keto Cheesy Bacon Ranch Potatoes",
    "Keto Lemon Garlic Butter Steak",
    "Keto Zucchini Breakfast Hash",
    "Keto Cheesy Cauliflower Bread",
    "Keto Peanut Butter Chocolate Smoothie",
    "Keto Chicken Parmesan Casserole",
    "Keto Avocado Chicken Bacon Ranch Salad",
    "Keto Almond Flour Pumpkin Muffins",
    "Keto Bacon-Wrapped Stuffed Chicken Breast",
    "Keto Cauliflower Crust Pizza",
    "Keto Chocolate Peanut Butter Bars",
    "Keto Creamy Garlic Parmesan Brussels Sprouts",
    "Keto Coconut Flour Blueberry Pancake Bites",
    "Keto Cheesy Bacon Ranch Brussels Sprouts",
    "Keto Lemon Garlic Butter Shrimp Pasta",
    "Keto Zucchini Banana Bread",
    "Keto Cheesy Cauliflower Rice Stuffed Peppers",
    "Keto Peanut Butter Chocolate Fat Bombs",
    "Keto Chicken and Broccoli Stir-Fry",
    "Keto Avocado Salmon Salad",
    "Keto Almond Flour Chocolate Donuts",
    "Keto Bacon-Wrapped Scallops",
    "Keto Cauliflower Nachos",
    "Keto Chocolate Peanut Butter Cups",
    "Keto Creamy Mushroom Chicken",
    "Keto Coconut Flour Blueberry Pancake Muffins",
    "Keto Cheesy Bacon Ranch Zucchini Fritters",
    "Keto Lemon Blueberry Pancakes",
    "Keto Zucchini Taco Boats",
    "Keto Cheesy Cauliflower Tater Tots",
    "Keto Peanut Butter Chocolate Chia Pudding",
    "Keto Chicken Alfredo Stuffed Spaghetti Squash",
    "Keto Avocado Egg Salad Lettuce Wraps",
    "Keto Almond Flour Chocolate Cupcakes",
    "Keto Bacon-Wrapped Stuffed Jalapenos",
    "Keto Cauliflower Grits",
    "Keto Chocolate Peanut Butter Protein Balls",
    "Keto Creamy Sun-Dried Tomato Chicken Skillet",
    "Keto Coconut Flour Cinnamon Rolls",
    "Keto Cheesy Bacon Ranch Zucchini Casserole",
    "Keto Lemon Garlic Butter Shrimp and Asparagus",
    "Keto Zucchini Taco Casserole",
    "Keto Cheesy Cauliflower Breadsticks with Marinara",
    "Keto Peanut Butter Chocolate Chip Smoothie",
    "Keto Chicken Fajita Casserole",
    "Keto Avocado Cucumber Salad",
    "Keto Almond Flour Chocolate Fat Bombs",
    "Keto Bacon-Wrapped Chicken Thighs",
    "Keto Cauliflower Potato Salad",
    "Keto Chocolate Peanut Butter Fat Bomb Smoothie",
    "Keto Creamy Pesto Zucchini Noodles",
    "Keto Coconut Flour Pancake Bites",
    "Keto Cheesy Bacon Ranch Cauliflower Rice",
    "Keto Lemon Blueberry Pancake Muffins",
    "Keto Zucchini Bread French Toast",
    "Keto Cheesy Cauliflower Tots with Bacon",
    "Keto Peanut Butter Chocolate Protein Balls",
    "Keto Chicken Caesar Salad",
    "Keto Avocado Egg Salad Stuffed Tomatoes",
    "Keto Almond Flour Blueberry Donuts",
    "Keto Bacon-Wrapped Pork Tenderloin",
    "Keto Cauliflower Potato Mash",
    "Keto Chocolate Peanut Butter Fat Bomb Bars",
    "Keto Creamy Garlic Parmesan Brussels Sprouts Bake",
    "Keto Coconut Flour Pumpkin Bread",
    "Keto Cheesy Bacon Ranch Cauliflower",
    "Keto Lemon Blueberry Pancake Bites",
    "Keto Zucchini Noodle Carbonara",
    "Keto Cheesy Cauliflower Rice Stuffed Tomatoes",
    "Keto Peanut Butter Chocolate Chaffle",
    "Keto Chicken and Mushroom Skillet",
    "Keto Avocado Egg Salad Lettuce Cups",
    "Keto Almond Flour Blueberry Muffin Bread",
    "Keto Bacon-Wrapped Chicken Breast",
    "Keto Cauliflower Buffalo Chicken Casserole",
    "Keto Chocolate Peanut Butter Fat Bomb Smoothie",
    "Keto Creamy Spinach and Sausage Stuffed Mushrooms",
    "Keto Coconut Flour Chocolate Chip Cookies",
    "Keto Cheesy Bacon Ranch Brussels Sprouts Bake",
    "Keto Lemon Garlic Butter Shrimp and Broccoli",
    "Keto Zucchini Noodle Shrimp Scampi",
    "Keto Cheesy Cauliflower Rice and Broccoli Casserole",
    "Keto Peanut Butter Chocolate Fat Bomb Bars",
    "Keto Chicken Bacon Ranch Stuffed Peppers",
    "Keto Avocado Bacon Ranch Chicken Salad",
    "Keto Almond Flour Blueberry Pancake Bites",
    "Keto Bacon-Wrapped Jalapeno Popper Chicken",
    "Keto Cauliflower Rice Burrito Bowl",
    "Keto Chocolate Peanut Butter Smoothie Bowl",
    "Keto Creamy Garlic Parmesan Mushrooms",
    "Keto Coconut Flour Chocolate Donut Holes",
    "Keto Cheesy Bacon Ranch Zucchini Noodles",
    "Keto Lemon Blueberry Pancake Breakfast Casserole",
    "Keto Zucchini Noodle Alfredo with Chicken",
    "Keto Cheesy Cauliflower Rice Stuffed Bell Peppers",
    "Keto Peanut Butter Chocolate Chip Chaffle",
    "Keto Chicken Alfredo Zucchini Boats",
    "Keto Avocado Chicken Salad Lettuce Wraps",
    "Keto Almond Flour Blueberry Pancake Muffins",
    "Keto Bacon-Wrapped Shrimp Skewers",
    "Keto Cauliflower Rice Sushi Rolls",
    "Keto Chocolate Peanut Butter Cupcakes",
    "Keto Creamy Pesto Zucchini Noodles with Shrimp",
    "Keto Coconut Flour Pumpkin Muffins",
    "Keto Cheesy Bacon Ranch Zucchini Chips",
    "Keto Lemon Garlic Butter Shrimp Pasta with Zoodles",
    "Keto Zucchini Banana Bread Muffins",
    "Keto Cheesy Cauliflower Bread Bites",
    "Keto Peanut Butter Chocolate Mug Cake",
    "Keto Chicken Enchilada Stuffed Zucchini Boats",
    "Keto Avocado Tuna Salad Lettuce Wraps",
    "Keto Almond Flour Blueberry Donut Holes",
    "Keto Bacon-Wrapped Meatballs",
    "Keto Cauliflower Rice Jambalaya",
    "Keto Chocolate Peanut Butter Ice Cream",
    "Keto Creamy Sun-Dried Tomato Chicken Zucchini Noodles",
    "Keto Coconut Flour Blueberry Pancake Bites",
    "Keto Cheesy Bacon Ranch Zucchini Rolls",
    "Keto Lemon Blueberry Pancake Roll-Ups",
    "Keto Zucchini Noodle Pad Thai",
    "Keto Cheesy Cauliflower Muffins",
    "Keto Peanut Butter Chocolate Chip Mug Cake",
    "Keto Chicken Fajita Stuffed Bell Peppers",
    "Keto Avocado Salmon Cucumber Bites",
    "Keto Almond Flour Blueberry Muffin Bites",
    "Keto Bacon-Wrapped Steak Bites",
    "Keto Cauliflower Rice Stuffed Peppers",
    "Keto Chocolate Peanut Butter Chia Pudding Parfait",
    "Keto Creamy Garlic Parmesan Spinach",
    "Keto Coconut Flour Lemon Poppy Seed Muffins",
    "Keto Cheesy Bacon Ranch Zucchini Noodle Bake",
    "Keto Lemon Blueberry Pancake Roll-Ups",
    "Keto Zucchini Noodle Carbonara with Chicken",
    "Keto Cheesy Cauliflower Rice Balls",
    "Keto Peanut Butter Chocolate Chip Mug Brownie",
    "Keto Chicken Parmesan Stuffed Portobello Mushrooms",
    "Keto Avocado Bacon Ranch Deviled Eggs",
    "Keto Almond Flour Blueberry Pancake Roll-Ups",
    "Keto Bacon-Wrapped Stuffed Pork Chops",
    "Keto Cauliflower Rice Taco Skillet",
    "Keto Chocolate Peanut Butter Cheesecake Bars",
    "Keto Creamy Spinach and Sausage Stuffed Peppers",
    "Keto Coconut Flour Blueberry Muffin Bites",
    "Keto Cheesy Bacon Ranch Zucchini Noodle Casserole",
    "Keto Lemon Blueberry Pancake Breakfast Casserole",
    "Keto Zucchini Noodle Chicken Alfredo",
    "Keto Cheesy Cauliflower Breadsticks with Ranch",
    "Keto Peanut Butter Chocolate Chip Mug Muffin",
    "Keto Chicken Fajita Stuffed Zucchini Boats",
    "Keto Avocado Tuna Salad Cucumber Bites",
    "Keto Almond Flour Blueberry Pancake Roll-Ups",
    "Keto Bacon-Wrapped Stuffed Bell Peppers",
    "Keto Cauliflower Rice Sushi Bowls",
    "Keto Chocolate Peanut Butter Cheesecake Cups",
    "Keto Creamy Sun-Dried Tomato Chicken Zucchini Boat",
    "Keto Coconut Flour Lemon Blueberry Muffins",
    "Keto Cheesy Bacon Ranch Zucchini Boat Casserole",
    "Keto Lemon Blueberry Pancake Muffin Cups",
    "Keto Zucchini Noodle Chicken Stir-Fry",
    "Keto Cheesy Cauliflower Rice Balls with Marinara",
    "Keto Peanut Butter Chocolate Chip Mug Cookie",
    "Keto Chicken Parmesan Stuffed Zucchini Boats",
    "Keto Avocado Bacon Ranch Deviled Eggs",
    "Keto Almond Flour Blueberry Pancake Cups",
    "Keto Bacon-Wrapped Stuffed Mushrooms",
    "Keto Cauliflower Rice Taco Casserole",
    "Keto Chocolate Peanut Butter Cheesecake Fat Bombs",
    "Keto Creamy Spinach and Artichoke Stuffed Mushrooms",
    "Keto Coconut Flour Lemon Poppy Seed Donuts",
    "Keto Cheesy Bacon Ranch Zucchini Frittata",
    "Keto Lemon Blueberry Pancake Muffin Bites",
    "Keto Zucchini Noodle Chicken Teriyaki",
    "Keto Cheesy Cauliflower Breadsticks with Garlic",
    "Keto Peanut Butter Chocolate Chip Mug Cake",
    "Keto Chicken Fajita Stuffed Peppers",
    "Keto Avocado Tuna Salad Cucumber Cups",
    "Keto Almond Flour Blueberry Pancake Cups",
    "Keto Bacon-Wrapped Stuffed Jalapenos",
    "Keto Cauliflower Rice Sushi Rolls",
    "Keto Chocolate Peanut Butter Cupcakes",
    "Keto Creamy Pesto Zucchini Noodles with Shrimp",
    "Keto Coconut Flour Pumpkin Muffins",
    "Keto Cheesy Bacon Ranch Zucchini Chips",
    "Keto Lemon Garlic Butter Shrimp Pasta with Zoodles",
    "Keto Zucchini Banana Bread Muffins",
    "Keto Cheesy Cauliflower Bread Bites",
    "Keto Peanut Butter Chocolate Mug Cake",
    "Keto Chicken Enchilada Stuffed Zucchini Boats",
    "Keto Avocado Tuna Salad Lettuce Wraps",
    "Keto Almond Flour Blueberry Donut Holes",
    "Keto Bacon-Wrapped Meatballs",
    "Keto Cauliflower Rice Jambalaya",
    "Keto Chocolate Peanut Butter Ice Cream",
    "Keto Creamy Sun-Dried Tomato Chicken Zucchini Noodles",
    "Keto Coconut Flour Blueberry Pancake Bites",
    "Keto Cheesy Bacon Ranch Zucchini Rolls",
    "Keto Lemon Blueberry Pancake Roll-Ups",
    "Keto Zucchini Noodle Pad Thai",
    "Keto Cheesy Cauliflower Muffins",
    "Keto Peanut Butter Chocolate Chip Mug Cake",
    "Keto Chicken Fajita Stuffed Bell Peppers",
    "Keto Avocado Salmon Cucumber Bites",
    "Keto Almond Flour Blueberry Muffin Bites",
    "Keto Bacon-Wrapped Steak Bites",
    "Keto Cauliflower Rice Stuffed Peppers",
    "Keto Chocolate Peanut Butter Chia Pudding Parfait",
    "Keto Creamy Garlic Parmesan Spinach",
    "Keto Coconut Flour Lemon Poppy Seed Muffins",
    "Keto Cheesy Bacon Ranch Zucchini Noodle Bake",
    "Keto Lemon Blueberry Pancake Roll-Ups",
    "Keto Zucchini Noodle Carbonara with Chicken",
    "Keto Cheesy Cauliflower Rice Balls",
    "Keto Peanut Butter Chocolate Chip Mug Brownie",
    "Keto Chicken Parmesan Stuffed Portobello Mushrooms",
    "Keto Avocado Bacon Ranch Deviled Eggs",
    "Keto Almond Flour Blueberry Pancake Bites",
    "Keto Bacon-Wrapped Stuffed Pork Chops",
    "Keto Cauliflower Rice Taco Skillet",
    "Keto Chocolate Peanut Butter Cheesecake Bars",
    "Keto Creamy Spinach and Sausage Stuffed Peppers",
    "Keto Coconut Flour Blueberry Muffin Bites",
    "Keto Cheesy Bacon Ranch Zucchini Noodle Casserole",
    "Keto Lemon Blueberry Pancake Breakfast Casserole",
    "Keto Zucchini Noodle Chicken Alfredo",
    "Keto Cheesy Cauliflower Breadsticks with Ranch",
    "Keto Peanut Butter Chocolate Chip Mug Muffin",
    "Keto Chicken Fajita Stuffed Zucchini Boats",
    "Keto Avocado Tuna Salad Cucumber Bites",
    "Keto Almond Flour Blueberry Pancake Roll-Ups",
    "Keto Bacon-Wrapped Stuffed Bell Peppers",
    "Keto Cauliflower Rice Sushi Bowls",
    "Keto Chocolate Peanut Butter Cheesecake Cups",
    "Keto Creamy Sun-Dried Tomato Chicken Zucchini Boat",
    "Keto Coconut Flour Lemon Blueberry Muffins",
    "Keto Cheesy Bacon Ranch Zucchini Frittata",
    "Keto Lemon Blueberry Pancake Muffin Bites",
    "Keto Zucchini Noodle Chicken Teriyaki",
    "Keto Cheesy Cauliflower Breadsticks with Garlic",
    "Keto Peanut Butter Chocolate Chip Mug Cake",
    "Keto Chicken Fajita Stuffed Peppers",
    "Keto Avocado Tuna Salad Cucumber Cups",
    "Keto Almond Flour Blueberry Pancake Cups",
    "Keto Bacon-Wrapped Stuffed Mushrooms",
    "Keto Cauliflower Rice Taco Casserole",
    "Keto Chocolate Peanut Butter Cheesecake Fat Bombs",
    "Keto Creamy Spinach and Artichoke Stuffed Mushrooms",
    "Keto Coconut Flour Lemon Poppy Seed Donuts",
    "Keto Cheesy Bacon Ranch Zucchini Frittata",
    "Keto Lemon Blueberry Pancake Muffin Bites",
    "Keto Zucchini Noodle Chicken Teriyaki",
    "Keto Cheesy Cauliflower Breadsticks with Garlic",
    "Keto Peanut Butter Chocolate Chip Mug Cake",
    "Keto Chicken Fajita Stuffed Peppers",
    "Keto Avocado Tuna Salad Cucumber Cups",
    "Keto Almond Flour Blueberry Pancake Cups",
    "Keto Bacon-Wrapped Stuffed Mushrooms",
    "Keto Cauliflower Rice Taco Casserole",
    "Keto Chocolate Peanut Butter Cheesecake Fat Bombs",
    "Keto Creamy Spinach and Artichoke Stuffed Mushrooms",
    "Keto Coconut Flour Lemon Poppy Seed Donuts",
    "Keto Cheesy Bacon Ranch Zucchini Frittata",
    "Keto Lemon Blueberry Pancake Muffin Bites",
    "Keto Zucchini Noodle Chicken Teriyaki",
    "Keto Cheesy Cauliflower Breadsticks with Garlic",
    "Keto Peanut Butter Chocolate Chip Mug Cake",
    "Keto Chicken Fajita Stuffed Peppers",
    "Keto Avocado Tuna Salad Cucumber Cups",
    "Keto Almond Flour Blueberry Pancake Cups",
    "Keto Bacon-Wrapped Stuffed Mushrooms",
    "Keto Cauliflower Rice Taco Casserole",
    "Keto Chocolate Peanut Butter Cheesecake Fat Bombs",
    "Keto Creamy Spinach and Artichoke Stuffed Mushrooms",
    "Keto Coconut Flour Lemon Poppy Seed Donuts",
    "Keto Cheesy Bacon Ranch Zucchini Frittata",
    "Keto Lemon Blueberry Pancake Muffin Bites",
    "Keto Zucchini Noodle Chicken Teriyaki",
    "Keto Cheesy Cauliflower Breadsticks with Garlic",
    "Keto Peanut Butter Chocolate Chip Mug Cake",
    "Keto Chicken Fajita Stuffed Peppers",
    "Keto Avocado Tuna Salad Cucumber Cups",
    "Keto Almond Flour Blueberry Pancake Cups",
    "Keto Bacon-Wrapped Stuffed Mushrooms",
    "Keto Cauliflower Rice Taco Casserole",
    "Keto Chocolate Peanut Butter Cheesecake Fat Bombs",
    "Keto Creamy Spinach and Artichoke Stuffed Mushrooms",
    "Keto Coconut Flour Lemon Poppy Seed Donuts",
    "Keto Cheesy Bacon Ranch Zucchini Frittata",
    "Keto Lemon Blueberry Pancake Muffin Bites",
    "Keto Zucchini Noodle Chicken Teriyaki",
    "Keto Cheesy Cauliflower Breadsticks with Garlic",
    "Keto Peanut Butter Chocolate Chip Mug Cake",
    "Keto Chicken Fajita Stuffed Peppers",
    "Keto Avocado Tuna Salad Cucumber Cups",
    "Keto Almond Flour Blueberry Pancake Cups",
    "Keto Bacon-Wrapped Stuffed Mushrooms",
    "Keto Cauliflower Rice Taco Casserole",
    "Keto Chocolate Peanut Butter Cheesecake Fat Bombs",
    "Keto Creamy Spinach and Artichoke Stuffed Mushrooms",
    "Keto Coconut Flour Lemon Poppy Seed Donuts",
    "Keto Cheesy Bacon Ranch Zucchini Frittata",
    "Keto Lemon Blueberry Pancake Muffin Bites",
    "Keto Zucchini Noodle Chicken Teriyaki",
    "Keto Cheesy Cauliflower Breadsticks with Garlic",
    "Keto Peanut Butter Chocolate Chip Mug Cake",
    "Keto Chicken Fajita Stuffed Peppers",
    "Keto Avocado Tuna Salad Cucumber Cups",
    "Keto Almond Flour Blueberry Pancake Cups",
    "Keto Bacon-Wrapped Stuffed Mushrooms",
    "Keto Cauliflower Rice Taco Casserole",
    "Keto Chocolate Peanut Butter Cheesecake Fat Bombs",
    "Keto Creamy Spinach and Artichoke Stuffed Mushrooms",
    "Keto Coconut Flour Lemon Poppy Seed Donuts",
    "Keto Cheesy Bacon Ranch Zucchini Frittata",
    "Keto Lemon Blueberry Pancake Muffin Bites",
    "Keto Zucchini Noodle Chicken Teriyaki",
    "Keto Cheesy Cauliflower Breadsticks with Garlic",
    "Keto Peanut Butter Chocolate Chip Mug Cake",
    "Keto Chicken Fajita Stuffed Peppers",
    "Keto Avocado Tuna Salad Cucumber Cups",
    "Keto Almond Flour Blueberry Pancake Cups",
    "Keto Bacon-Wrapped Stuffed Mushrooms",
    "Keto Cauliflower Rice Taco Casserole",
    "Keto Chocolate Peanut Butter Cheesecake Fat Bombs",
    "Keto Creamy Spinach and Artichoke Stuffed Mushrooms",
    "Keto Coconut Flour Lemon Poppy Seed Donuts",
    "Keto Cheesy Bacon Ranch Zucchini Frittata",
    "Keto Lemon Blueberry Pancake Muffin Bites",
    "Keto Zucchini Noodle Chicken Teriyaki",
    "Keto Cheesy Cauliflower Breadsticks with Garlic",
    "Keto Peanut Butter Chocolate Chip Mug Cake",
    "Keto Chicken Fajita Stuffed Peppers"],

    // Mediterranean
    [
      "Greek Salad",
      "Mediterranean Chicken Skewers",
      "Hummus with Pita Bread",
      "Tabbouleh",
      "Baba Ganoush",
      "Mediterranean Grilled Vegetables",
      "Falafel",
      "Moussaka",
      "Tzatziki Sauce",
      "Spanakopita",
      "Lamb Kebabs",
      "Shakshuka",
      "Couscous Salad",
      "Feta Stuffed Peppers",
      "Lemon Garlic Shrimp",
      "Chicken Shawarma",
      "Greek Lemon Potatoes",
      "Stuffed Grape Leaves",
      "Mediterranean Quinoa Salad",
      "Olive Tapenade",
      "Lamb Gyro",
      "Eggplant Parmesan",
      "Mediterranean Baked Fish",
      "Greek Yogurt with Honey and Nuts",
      "Mediterranean Roasted Chicken",
      "Mushroom Risotto",
      "Lemon Herb Roasted Vegetables",
      "Greek Lentil Soup",
      "Spinach and Feta Stuffed Chicken Breast",
      "Mediterranean Chickpea Salad",
      "Zucchini and Feta Fritters",
      "Mediterranean Stuffed Bell Peppers",
      "Greek Lemon Chicken Soup",
      "Mediterranean Pasta Salad",
      "Lentil and Vegetable Moussaka",
      "Herb-Marinated Grilled Tofu",
      "Mediterranean Rice Pilaf",
      "Fattoush Salad",
      "Mediterranean Lamb Chops",
      "Artichoke and Olive Pizza",
      "Roasted Red Pepper Dip",
      "Greek Spinach Pie",
      "Mediterranean Stuffed Zucchini",
      "Quinoa Tabbouleh",
      "Greek Style Grilled Eggplant",
      "Mediterranean Cucumber Salad",
      "Greek Lemon Rice",
      "Mediterranean Chickpea Stew",
      "Herb Roasted Leg of Lamb",
      "Mediterranean Orzo Salad",
    ],
    // LowCarb: 
    [
      "Grilled Chicken with Asparagus",
      "Zucchini Noodles with Pesto",
      "Cauliflower Fried Rice",
      "Broccoli and Cheese Stuffed Chicken Breast",
      "Baked Salmon with Lemon and Dill",
      "Egg Muffins with Spinach and Bacon",
      "Stuffed Bell Peppers with Ground Turkey",
      "Avocado Shrimp Salad",
      "Cauliflower Crust Pizza",
      "Keto Meatballs",
      "Garlic Butter Steak Bites",
      "Spinach and Feta Stuffed Chicken",
      "Baked Cod with Herbs and Lemon",
      "Chicken Lettuce Wraps",
      "Cauliflower Mac and Cheese",
      "Zucchini Lasagna",
      "Greek Salad with Grilled Chicken",
      "Cheesy Broccoli Soup",
      "Turkey Meatloaf",
      "Sautéed Shrimp with Garlic and Butter",
      "Cabbage and Sausage Skillet",
      "Baked Parmesan Crusted Chicken",
      "Cauliflower Mashed Potatoes",
      "Keto Taco Casserole",
      "Italian Stuffed Zucchini Boats",
      "Grilled Lemon Herb Chicken",
      "Eggplant Lasagna",
      "Beef and Broccoli Stir-Fry",
      "Cucumber Avocado Salad",
      "Cheesy Cauliflower Rice",
      "Bacon-Wrapped Stuffed Chicken Breast",
      "Salmon Cakes",
      "Zucchini Fritters",
      "Lemon Garlic Butter Shrimp",
      "Turkey Taco Lettuce Wraps",
      "Cauliflower Alfredo Sauce",
      "Stuffed Portobello Mushrooms",
      "Garlic Butter Steak and Veggies",
      "Chicken and Broccoli Casserole",
      "Zucchini Noodle Stir-Fry",
      "Baked Garlic Parmesan Salmon",
      "Buffalo Chicken Lettuce Wraps",
      "Mediterranean Cucumber Salad",
      "Cheesy Spinach Stuffed Chicken Breast",
      "Cauliflower Rice Sushi Rolls",
      "Beef and Cabbage Stir-Fry",
      "Keto Broccoli Cheddar Soup",
      "Lemon Herb Grilled Shrimp",
      "Zucchini Enchiladas",
    ],
    // Pescatarian:
     [
      "Grilled Salmon with Lemon and Dill",
      "Shrimp Scampi",
      "Tuna Salad Lettuce Wraps",
      "Seared Scallops with Garlic and Butter",
      "Miso Glazed Cod",
      "Baked Lemon Herb Tilapia",
      "Fish Tacos with Mango Salsa",
      "Crispy Baked Coconut Shrimp",
      "Salmon Cakes with Dill Sauce",
      "Lemon Garlic Shrimp Pasta",
      "Sesame Ginger Tofu Stir-Fry",
      "Greek Style Baked Cod",
      "Spicy Tuna Rolls",
      "Coconut Lime Shrimp",
      "Quinoa and Black Bean Stuffed Bell Peppers",
      "Teriyaki Salmon",
      "Lemon Herb Grilled Shrimp Skewers",
      "Zucchini and Shrimp Stir-Fry",
      "Avocado Tuna Salad",
      "Baked Halibut with Garlic and Herbs",
      "Mediterranean Stuffed Bell Peppers",
      "Crispy Baked Fish and Chips",
      "Lemon Garlic Butter Shrimp Pasta",
      "Cauliflower Rice Sushi Rolls",
      "Blackened Mahi-Mahi",
      "Tofu and Vegetable Stir-Fry",
      "Seared Ahi Tuna",
      "Spicy Shrimp Lettuce Wraps",
      "Mediterranean Quinoa Salad",
      "Lemon Herb Grilled Salmon",
      "Tuna Poke Bowl",
      "Cilantro Lime Shrimp",
      "Vegetable and Tofu Stir-Fry",
      "Coconut Curry Shrimp",
      "Baked Lemon Herb Salmon",
      "Lemon Garlic Shrimp and Asparagus",
      "Shrimp and Avocado Salad",
      "Greek Style Baked Salmon",
      "Sesame Crusted Tofu",
      "Grilled Shrimp Skewers with Chimichurri Sauce",
      "Avocado and Tuna Stuffed Bell Peppers",
      "Teriyaki Tofu",
      "Baked Cod with Tomatoes and Olives",
      "Mediterranean Zucchini and Feta Fritters",
      "Crispy Coconut Tofu",
      "Shrimp and Quinoa Stuffed Bell Peppers",
      "Lemon Herb Grilled Shrimp",
      "Zucchini and Shrimp Stir-Fry",
    ],
    // Vegetarian: 
    [
      "Vegetable Stir-Fry",
      "Caprese Salad",
      "Eggplant Parmesan",
      "Quinoa Stuffed Bell Peppers",
      "Spinach and Feta Stuffed Mushrooms",
      "Vegetarian Chili",
      "Black Bean Enchiladas",
      "Vegetable Curry",
      "Mushroom Risotto",
      "Vegetable Lasagna",
      "Stuffed Portobello Mushrooms",
      "Cauliflower Fried Rice",
      "Greek Salad",
      "Vegetable Biryani",
      "Caprese Stuffed Avocado",
      "Sweet Potato and Black Bean Tacos",
      "Vegetable Pad Thai",
      "Eggplant Involtini",
      "Butternut Squash Risotto",
      "Vegetable Stir-Fried Noodles",
      "Quinoa and Vegetable Stuffed Zucchini",
      "Mushroom and Spinach Quesadillas",
      "Vegetable Fajitas",
      "Zucchini and Corn Fritters",
      "Caprese Stuffed Portobello Mushrooms",
      "Cauliflower and Chickpea Curry",
      "Vegetable Bibimbap",
      "Stuffed Bell Peppers with Quinoa and Black Beans",
      "Vegetable Paella",
      "Eggplant and Chickpea Tagine",
      "Mushroom and Spinach Stuffed Shells",
      "Vegetable Tikka Masala",
      "Zucchini Noodle Caprese",
      "Vegetable and Lentil Shepherd's Pie",
      "Sweet Potato and Black Bean Burritos",
      "Vegetable Bolognese",
      "Butternut Squash and Spinach Lasagna",
      "Vegetable Lo Mein",
      "Quinoa and Black Bean Burgers",
      "Mushroom and Spinach Stroganoff",
      "Vegetable Enchiladas",
      "Cauliflower and Chickpea Tagine",
      "Vegetable and Lentil Curry",
      "Sweet Potato and Black Bean Quesadillas",
      "Vegetable Bibimbap",
      "Zucchini and Corn Tacos",
      "Vegetable Stir-Fry with Tofu",
      "Eggplant and Chickpea Curry",
      "Mushroom and Spinach Lasagna",
      "Vegetable Pad Thai",
    ]
]

export default recipes;